"""Deck note injector (parametrized over ``DeckConfig``).

Copies the source deck to ``[repo-checked].pptx`` (the source is never
modified) and writes a structured ``[Repo check]`` block into the speaker
notes of every slide that has a registry check pinned to it (plus the
relevant-but-unmodeled slides for known gaps — CEBA only).

The injection is idempotent (CON-003): a delimiter
``=== [Repo check] (generated) ===`` is detected and everything below it
is replaced; any author notes above the delimiter are preserved.

Usage (from repo root):
    .venv\\Scripts\\python.exe scripts/python/integration/ceba_deck/inject_repo_notes.py
    .venv\\Scripts\\python.exe scripts/python/integration/ceba_deck/inject_repo_notes.py --deck july
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[4]
SCRIPTS_PYTHON = REPO_ROOT / "scripts" / "python"
if str(SCRIPTS_PYTHON) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_PYTHON))
from integration.ceba_deck.deck_config import get_deck

DELIMITER = "=== [Repo check] (generated) ==="
VERDICT_ICON = {
    "ok": "✅",
    "warn": "⚠️",
    "info": "ℹ️",
    "bad": "❌",
    "skip": "➖",
    "err": "💥",
    "calibrated": "🔧",
}
KNOWN_GAP_NOTE = (
    "This slide is a relevant-but-unmodeled topic for the repo (DEC-006).\n"
    "No quantitative check was attempted; the repo does not model this.\n"
    "See the deck's `reports/..._repo_check.md` for the full gap description."
)


def _format_value(v: Any) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        if abs(v) < 0.01 and v != 0:
            return f"{v:.2e}"
        if abs(v) >= 1000:
            return f"{v:,.0f}"
        return f"{v:,.4f}".rstrip("0").rstrip(".")
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, list):
        if len(v) > 8:
            return f"[…{len(v)} items…]"
        return "[" + ", ".join(_format_value(x) for x in v) + "]"
    return str(v)


def _block_for_check(check: dict) -> str:
    icon = VERDICT_ICON.get(check["verdict"], "?")
    lines = [f"{icon} {check['id']}  (slide {check['slide']}, bucket {check['bucket']})"]
    lines.append(f"  claim     : {check['claim']}")
    lines.append(f"  deck      : {_format_value(check['deck_value'])} {check['deck_unit']}".rstrip())
    if check.get("deck_citation"):
        lines.append(f"  deck cite : {check['deck_citation']}")
    lines.append(f"  repo      : {_format_value(check['repo_value'])}")
    delta = check.get("delta_pct")
    if delta is not None:
        lines.append(f"  delta     : {delta:+.2%}")
    lines.append(f"  repo fn   : {check['repo_fn']}  ({check['repo_source_ref']})")
    if check.get("assumptions"):
        for a in check["assumptions"]:
            lines.append(f"  assumed   : {a}")
    if check.get("takeaway"):
        lines.append(f"  takeaway  : {check['takeaway']}")
    extra = check.get("notes", {}).get("extra") or {}
    if extra:
        # Trim verbose extras to a couple of lines so the slide note stays scannable.
        kept = []
        for k, v in extra.items():
            if isinstance(v, list) and len(v) > 6:
                kept.append(f"  {k}     : [list of {len(v)}]")
            elif isinstance(v, str) and len(v) > 80:
                kept.append(f"  {k}     : {v[:77]}…")
            else:
                kept.append(f"  {k}     : {v}")
        if kept:
            lines.append("  ---")
            lines.extend(kept[:4])
    return "\n".join(lines)


def _block_for_known_gap(gap: dict) -> str:
    lines = [f"➖ {gap['id']}  (slide {gap['slide']}, out of repo scope)"]
    lines.append(f"  topic  : {gap['topic']}")
    lines.append(f"  note   : {gap['note']}")
    lines.append(f"  advise : {KNOWN_GAP_NOTE}")
    return "\n".join(lines)


def _build_note_block(slide_index: int, checks: list[dict], gaps: list[dict], config) -> str:
    """Compose the structured [Repo check] block for one slide."""
    relevant_checks = [c for c in checks if c["slide"] == slide_index]
    relevant_gaps = [g for g in gaps if g["slide"] == slide_index]
    if not relevant_checks and not relevant_gaps:
        return ""
    parts = [
        f"[Repo check] Slide {slide_index} — {len(relevant_checks)} check(s) + "
        f"{len(relevant_gaps)} known gap(s)",
        f"Source: {config.results_json.relative_to(REPO_ROOT)} (orchestrator + plan).",
        f"Generated by scripts/python/integration/ceba_deck/inject_repo_notes.py --deck {config.key}.",
        "",
    ]
    if relevant_checks:
        parts.append("--- checks ---")
        for c in relevant_checks:
            parts.append(_block_for_check(c))
    if relevant_gaps:
        parts.append("")
        parts.append("--- known gaps ---")
        for g in relevant_gaps:
            parts.append(_block_for_known_gap(g))
    return "\n".join(parts)


def _replace_repo_block(notes_text: str, new_block: str) -> str:
    """Idempotent replace: keep author notes above DELIMITER, replace everything below."""
    if DELIMITER in notes_text:
        before = notes_text.split(DELIMITER, 1)[0]
        return f"{before.rstrip()}\n\n{DELIMITER}\n{new_block}".rstrip() + "\n"
    if not notes_text.strip():
        return f"{DELIMITER}\n{new_block}".rstrip() + "\n"
    return f"{notes_text.rstrip()}\n\n{DELIMITER}\n{new_block}".rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--deck",
        choices=("ceba", "july"),
        default="ceba",
        help="Which deck to inject notes into (default: ceba).",
    )
    parser.add_argument(
        "--src",
        type=Path,
        default=None,
        help="Source deck path (read-only). Defaults to <deck_config>.source_pptx.",
    )
    parser.add_argument(
        "--dst",
        type=Path,
        default=None,
        help="Output deck path (will be created/overwritten). Defaults to <deck_config>.out_pptx.",
    )
    parser.add_argument(
        "--results",
        type=Path,
        default=None,
        help="Results JSON path. Defaults to <deck_config>.results_json.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="If set, do not write the output deck; just report what would be injected.",
    )
    args = parser.parse_args(argv)

    config = get_deck(args.deck)
    src = args.src or config.source_pptx
    dst = args.dst or config.out_pptx
    results = args.results or config.results_json

    if not src.exists():
        print(f"source deck not found: {src}", file=sys.stderr)
        return 1
    if not results.exists():
        print(f"results JSON not found: {results}", file=sys.stderr)
        return 1

    data = json.loads(results.read_text(encoding="utf-8"))
    checks = data["checks"]
    known_gaps = data.get("known_gaps", [])
    slides_to_annotate = sorted(
        {c["slide"] for c in checks} | {g["slide"] for g in known_gaps}
    )
    print(
        f"[inject_repo_notes] deck={config.key} | {len(checks)} checks + "
        f"{len(known_gaps)} known gaps → {len(slides_to_annotate)} slides to annotate",
        flush=True,
    )

    if args.dry_run:
        for slide_idx in slides_to_annotate:
            block = _build_note_block(slide_idx, checks, known_gaps, config)
            print(f"--- slide {slide_idx} ({len(block)} chars) ---")
            print(block)
            print()
        return 0

    # Always copy fresh from source (CON-002: never modify the source).
    if dst.exists():
        try:
            dst.unlink()
        except PermissionError as exc:
            print(
                f"[inject_repo_notes] destination {dst.name} is locked "
                f"(likely open in PowerPoint): {exc}. "
                f"Close the deck in PowerPoint and re-run, or pass --dst to a new path.",
                file=sys.stderr,
            )
            return 3
    shutil.copy2(src, dst)
    print(f"[inject_repo_notes] copied {src.name} → {dst.name}", flush=True)

    # Lazy import so --dry-run works without python-pptx.
    from pptx import Presentation

    prs = Presentation(str(dst))
    slides = list(prs.slides)
    annotated = 0
    for slide_idx_1based, slide in enumerate(slides, start=1):
        if slide_idx_1based not in slides_to_annotate:
            continue
        block = _build_note_block(slide_idx_1based, checks, known_gaps, config)
        notes_slide = slide.notes_slide  # lazily creates a notes slide if absent
        tf = notes_slide.notes_text_frame
        existing = tf.text or ""
        new_text = _replace_repo_block(existing, block)
        tf.text = new_text
        annotated += 1
    prs.save(str(dst))
    try:
        rel = dst.resolve().relative_to(REPO_ROOT)
    except ValueError:
        rel = dst
    print(
        f"[inject_repo_notes] annotated {annotated} slide(s); wrote {rel}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
